"""LaTeX table for the outpainting completion benchmark (Ch 2).

Reads outputs/evaluations/outpaint_compare_prior{off,on}.csv (from
eval_outpaint_compare.py) and emits publication/tables/outpaint_compare.tex
plus a compact CSV. Rows: models; column groups: hidden half (completion) and
full image, HDR + LDR PSNR and hidden LPIPS_HDR. Prior-off is the headline
(the z^2 fit prior is a no-op for latent-reset models); prior-on lands in the
CSV for the appendix.

    PYTHONPATH=. python scripts/figures/make_outpaint_table.py
"""

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EVALS = REPO / "outputs" / "evaluations"
OUT = REPO / "publication" / "tables"

LABELS = {
    "reni_pp": "RENI++ (original, log-domain)",
    "latent_reset_4cyc": "RENI++ latent-reset (4 cyc)",
    "w3_1cyc": "Two-bracket (1 cyc)",
    "w3_2cyc": "Two-bracket (2 cyc)",
    "tb_4cyc": "Two-bracket (4 cyc)",
    "ldrw2_4cyc": "Two-bracket 2$\\times$LDR (4 cyc)",
}
ORDER = ["reni_pp", "latent_reset_4cyc", "w3_1cyc", "w3_2cyc", "tb_4cyc", "ldrw2_4cyc"]


def load(prior: str):
    rows = list(csv.DictReader(open(EVALS / f"outpaint_compare_prior{prior}.csv")))
    return {(r["model"], r["region"]): r for r in rows}


def fmt(rows, model, region, key, best, decimals=2, lower=False):
    v = float(rows[(model, region)][key])
    s = f"{v:.{decimals}f}"
    is_best = (v <= best + 1e-9) if lower else (v >= best - 1e-9)
    return f"\\textbf{{{s}}}" if is_best else s


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    rows = load("off")

    def best(region, key, lower=False):
        vals = [float(rows[(m, region)][key]) for m in ORDER]
        return min(vals) if lower else max(vals)

    lines = [
        "% Generated by scripts/figures/make_outpaint_table.py -- do not edit by hand",
        "\\begin{tabular}{@{}lccccc@{}}",
        "\\toprule",
        "& \\multicolumn{3}{c}{Hidden half (completion)} & \\multicolumn{2}{c}{Full image} \\\\",
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}",
        "Model & PSNR$_{\\text{HDR}}$ $\\uparrow$ & PSNR$_{\\text{LDR}}$ $\\uparrow$ & "
        "LPIPS$_{\\text{HDR}}$ $\\downarrow$ & PSNR$_{\\text{HDR}}$ $\\uparrow$ & "
        "PSNR$_{\\text{LDR}}$ $\\uparrow$ \\\\",
        "\\midrule",
    ]
    csv_rows = [("model", "hidden_psnr_hdr", "hidden_psnr_ldr", "hidden_lpips_hdr",
                 "full_psnr_hdr", "full_psnr_ldr")]
    for m in ORDER:
        cells = [
            fmt(rows, m, "hidden", "psnr_hdr", best("hidden", "psnr_hdr")),
            fmt(rows, m, "hidden", "psnr_ldr", best("hidden", "psnr_ldr")),
            fmt(rows, m, "hidden", "lpips_hdr", best("hidden", "lpips_hdr", lower=True), 3, lower=True),
            fmt(rows, m, "full", "psnr_hdr", best("full", "psnr_hdr")),
            fmt(rows, m, "full", "psnr_ldr", best("full", "psnr_ldr")),
        ]
        lines.append(f"{LABELS[m]} & " + " & ".join(cells) + " \\\\")
        csv_rows.append((m,) + tuple(
            rows[(m, reg)][k] for reg, k in [("hidden", "psnr_hdr"), ("hidden", "psnr_ldr"),
                                             ("hidden", "lpips_hdr"), ("full", "psnr_hdr"),
                                             ("full", "psnr_ldr")]))
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "outpaint_compare.tex").write_text("\n".join(lines) + "\n")
    with open(OUT / "outpaint_compare.csv", "w", newline="") as fh:
        csv.writer(fh).writerows(csv_rows)
    print(f"[saved] {OUT / 'outpaint_compare.tex'}")
    print(f"[saved] {OUT / 'outpaint_compare.csv'}")


if __name__ == "__main__":
    main()
