"""LaTeX table for the LDR-observation completion benchmark (Chapter 2).

Reads outputs/evaluations/outpaint_frustum90x60_ldrfit.csv (from
eval_outpaint_ldrfit.py) and emits publication/tables/outpaint_ldrfit.tex
plus a compact CSV. Fits are made to a known-exposure clipped sRGB rendering
of the central 90x60-degree frustum; scoring is against the true HDR.

    PYTHONPATH=. python scripts/figures/make_outpaint_ldrfit_table.py
"""

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EVALS = REPO / "outputs" / "evaluations"
OUT = REPO / "publication" / "tables"

LABELS = {
    "sh_prior": "SH + Gaussian prior",
    "sg_prior": "SG + Gaussian prior",
    "reni_old": "RENI",
    "reni_pp": "Published RENI++",
    "w3_2cyc": "Two-bracket, channelwise (2 cyc)",
    "vnjoint_ortho_2cyc": "Two-bracket, joint GS frame (2 cyc, ours)",
}
ORDER = ["sh_prior", "sg_prior", "reni_old", "reni_pp", "w3_2cyc",
         "vnjoint_ortho_2cyc"]
SOURCE = "outpaint_frustum90x60_ldrfit.csv"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    rows = {}
    for r in csv.DictReader(open(EVALS / SOURCE)):
        rows[(r["model"], r["region"])] = r
    order = [m for m in ORDER if (m, "hidden") in rows]

    def best(region, key, lower=False):
        vals = [float(rows[(m, region)][key]) for m in order]
        return min(vals) if lower else max(vals)

    def fmt(m, region, key, lower=False, decimals=2):
        v = float(rows[(m, region)][key])
        s = f"{v:.{decimals}f}"
        b = best(region, key, lower)
        is_best = (v <= b + 1e-9) if lower else (v >= b - 1e-9)
        return f"\\textbf{{{s}}}" if is_best else s

    lines = [
        "% Generated by scripts/figures/make_outpaint_ldrfit_table.py -- do not edit by hand",
        "\\begin{tabular}{@{}lccccc@{}}",
        "\\toprule",
        "& \\multicolumn{2}{c}{Hidden region} & \\multicolumn{1}{c}{Observed region} "
        "& \\multicolumn{2}{c}{Full sphere} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-4}\\cmidrule(lr){5-6}",
        "Model & PSNR$_{\\text{HDR}}$ $\\uparrow$ & PSNR$_{\\text{LDR}}$ $\\uparrow$ & "
        "PSNR$_{\\text{HDR}}$ $\\uparrow$ & LPIPS$_{\\text{LDR}}$ $\\downarrow$ & "
        "Peak angle $\\downarrow$ \\\\",
        "\\midrule",
    ]
    csv_rows = [("model", "hidden_psnr_hdr", "hidden_psnr_ldr",
                 "visible_psnr_hdr", "full_lpips_ldr",
                 "full_peak_angle_error_deg")]
    for m in order:
        cells = [
            fmt(m, "hidden", "psnr_hdr"),
            fmt(m, "hidden", "psnr_ldr"),
            fmt(m, "visible", "psnr_hdr"),
            fmt(m, "full", "lpips_ldr", lower=True, decimals=3),
            fmt(m, "full", "peak_angle_error_deg", lower=True, decimals=1),
        ]
        lines.append(f"{LABELS[m]} & " + " & ".join(cells) + " \\\\")
        csv_rows.append((m,) + tuple(
            rows[(m, reg)][k] for reg, k in [
                ("hidden", "psnr_hdr"), ("hidden", "psnr_ldr"),
                ("visible", "psnr_hdr"), ("full", "lpips_ldr"),
                ("full", "peak_angle_error_deg")]))
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "outpaint_ldrfit.tex").write_text("\n".join(lines) + "\n")
    with open(OUT / "outpaint_ldrfit.csv", "w", newline="") as fh:
        csv.writer(fh).writerows(csv_rows)
    print(f"[saved] {OUT / 'outpaint_ldrfit.tex'}")
    print(f"[saved] {OUT / 'outpaint_ldrfit.csv'}")


if __name__ == "__main__":
    main()
