"""LaTeX table for the frustum completion benchmark (Chapter 2).

Reads outputs/evaluations/outpaint_frustum90x60_prioroff.csv (from
eval_outpaint_compare.py) and emits publication/tables/outpaint_frustum.tex
plus a compact CSV. The visible region is a central 90 by 60 degree pinhole
frustum; the remaining directions form the hidden completion region.

    PYTHONPATH=. python scripts/figures/make_outpaint_table.py
"""

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EVALS = REPO / "outputs" / "evaluations"
OUT = REPO / "publication" / "tables"

LABELS = {
    "sh": "SH (9th order)",
    "sh_prior": "SH + Gaussian prior",
    "sg": "SG (50 lobes)",
    "sg_prior": "SG + Gaussian prior",
    "reni_old": "RENI",
    "reni_pp": "Published RENI++",
    "logdom_1cyc": "Log-domain (50k)",
    "logdom_std_100k": "Log-domain, no reset (100k)",
    "logdom_2cyc": "Log-domain, reset (2 cyc)",
    "w3_2cyc": "Two-bracket, channelwise (2 cyc)",
    "vnjoint_2cyc": "Two-bracket, joint unnormalised (2 cyc)",
    "vnjoint_ortho_2cyc": "Two-bracket, joint GS frame (2 cyc, ours)",
}
ORDER = ["sh", "sh_prior", "sg", "sg_prior", "reni_old", "reni_pp",
         "logdom_1cyc", "logdom_std_100k", "logdom_2cyc", "w3_2cyc",
         "vnjoint_2cyc", "vnjoint_ortho_2cyc"]

# The historical six models live in the prioroff CSV; migration-era runs are
# evaluated into their own stems and merged here.
SOURCES = (
    "outpaint_frustum90x60_prioroff.csv",
    "outpaint_frustum90x60_vnjoint_ortho.csv",
    "outpaint_frustum90x60_baselines.csv",
    "outpaint_frustum90x60_sh_prior.csv",
    "outpaint_frustum90x60_sg_prior.csv",
    # Overrides the reni_old rows with the learnt rows' own-quantile LDR
    # exposure convention (the gtq run stays for the sh/sg rows).
    "outpaint_frustum90x60_reni_old_predq.csv",
)


def load():
    merged = {}
    for name in SOURCES:
        path = EVALS / name
        if not path.exists():
            continue
        for r in csv.DictReader(open(path)):
            merged[(r["model"], r["region"])] = r
    return merged


def fmt(rows, model, region, key, best, decimals=2, lower=False):
    v = float(rows[(model, region)][key])
    s = f"{v:.{decimals}f}"
    is_best = (v <= best + 1e-9) if lower else (v >= best - 1e-9)
    return f"\\textbf{{{s}}}" if is_best else s


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    rows = load()
    order = [m for m in ORDER if (m, "hidden") in rows]
    missing = [m for m in ORDER if m not in order]
    if missing:
        print(f"[skip] rows without eval CSVs: {missing}")

    def best(region, key, lower=False):
        vals = [float(rows[(m, region)][key]) for m in order]
        return min(vals) if lower else max(vals)

    lines = [
        "% Generated by scripts/figures/make_outpaint_table.py -- do not edit by hand",
        "\\begin{tabular}{@{}lcccccc@{}}",
        "\\toprule",
        "& \\multicolumn{2}{c}{Hidden region} & \\multicolumn{1}{c}{Observed region} "
        "& \\multicolumn{3}{c}{Full sphere} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-4}\\cmidrule(lr){5-7}",
        "Model & PSNR$_{\\text{HDR}}$ $\\uparrow$ & PSNR$_{\\text{LDR}}$ $\\uparrow$ & "
        "PSNR$_{\\text{LDR}}$ $\\uparrow$ & PSNR$_{\\text{HDR}}$ $\\uparrow$ & "
        "PSNR$_{\\text{LDR}}$ $\\uparrow$ & LPIPS$_{\\text{LDR}}$ $\\downarrow$ \\\\",
        "\\midrule",
    ]
    csv_rows = [("model", "hidden_psnr_hdr", "hidden_psnr_ldr", "visible_psnr_ldr",
                 "full_psnr_hdr", "full_psnr_ldr", "full_lpips_ldr")]
    for m in order:
        cells = [
            fmt(rows, m, "hidden", "psnr_hdr", best("hidden", "psnr_hdr")),
            fmt(rows, m, "hidden", "psnr_ldr", best("hidden", "psnr_ldr")),
            fmt(rows, m, "visible", "psnr_ldr", best("visible", "psnr_ldr")),
            fmt(rows, m, "full", "psnr_hdr", best("full", "psnr_hdr")),
            fmt(rows, m, "full", "psnr_ldr", best("full", "psnr_ldr")),
            fmt(rows, m, "full", "lpips_ldr", best("full", "lpips_ldr", lower=True),
                decimals=3, lower=True),
        ]
        lines.append(f"{LABELS[m]} & " + " & ".join(cells) + " \\\\")
        csv_rows.append((m,) + tuple(
            rows[(m, reg)][k] for reg, k in [("hidden", "psnr_hdr"), ("hidden", "psnr_ldr"),
                                             ("visible", "psnr_ldr"), ("full", "psnr_hdr"),
                                             ("full", "psnr_ldr"), ("full", "lpips_ldr")]))
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "outpaint_frustum.tex").write_text("\n".join(lines) + "\n")
    with open(OUT / "outpaint_frustum.csv", "w", newline="") as fh:
        csv.writer(fh).writerows(csv_rows)
    print(f"[saved] {OUT / 'outpaint_frustum.tex'}")
    print(f"[saved] {OUT / 'outpaint_frustum.csv'}")


if __name__ == "__main__":
    main()
