"""Ablation tables (thesis Tables 2.4 and 2.7).

Evaluates the paper archive's ablation checkpoints with the same metric
machinery as the main comparison table (generate_figures.ModelLoader +
pipeline eval):

  Table 2.4 (architecture/training ablations, PSNR per latent dim):
    RENI (old, retrained 50k) -> +data aug -> +transformer decoder
    -> +scale-invariance (= RENI++ final)
  Table 2.7 (equivariance ablation at D=300): none / SO2 (final) / SO3

    PYTHONPATH=. python scripts/figures/make_ablation_tables.py
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "publication"))

from generate_figures import FigureConfig, ModelLoader  # noqa: E402
from reni.utils.checkpoint_locator import find_checkpoint  # noqa: E402

DIMS = (9, 36, 49, 100)
ABLATION_ROWS = [
    ("RENI (retrained, 50k)", "ablations/1_old_reni_50k_steps"),
    ("+ data augmentation", "ablations/2_data_aug"),
    ("+ transformer decoder", "ablations/3_transformer_decoder"),
    ("+ scale-invariant loss", "ablations/4_scale_inv"),
    ("RENI++ (final)", "reni_plus_plus_models"),
]
EQUIVARIANCE_ROWS = [
    ("None", "ablations/equivariance/none"),
    ("SO(3)", "ablations/equivariance/so3"),
    ("SO(2) (RENI++)", "reni_plus_plus_models/latent_dim_100"),
]


def evaluate(loader, rel):
    try:
        path = find_checkpoint(rel)
        pipeline, _, model = loader.load_model(path)
    except FileNotFoundError as e:
        print(f"[missing] {rel}: {e}")
        return None
    if hasattr(model.field, "latent_dim"):
        metrics = pipeline.get_average_eval_image_metrics(optimise_latents=False)
    else:
        metrics = pipeline.get_average_eval_image_metrics()
    return {k: float(v) for k, v in metrics.items() if "psnr" in k}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--output", type=Path,
                        default=REPO_ROOT / "publication" / "tables")
    args = parser.parse_args()

    config = FigureConfig()
    config.device = args.device
    loader = ModelLoader(config)
    args.output.mkdir(parents=True, exist_ok=True)
    cache_path = args.output / "ablations.metrics.json"
    cache = json.loads(cache_path.read_text()) if cache_path.exists() else {}

    def get(rel):
        if rel not in cache:
            print(f"[eval] {rel}")
            cache[rel] = evaluate(loader, rel)
            cache_path.write_text(json.dumps(cache, indent=2))
        return cache[rel]

    # ---- Table 2.4: architecture/training ablations --------------------
    lines = ["% Generated by scripts/figures/make_ablation_tables.py",
             "\\begin{tabular}{| l | " + "c | " * len(DIMS) + "}", "\\hline",
             "Model & " + " & ".join(f"$D={3*d}$" for d in DIMS) + " \\\\",
             "\\hline"]
    for label, base in ABLATION_ROWS:
        cells = []
        for d in DIMS:
            m = get(f"{base}/latent_dim_{d}")
            cells.append(f"{m['psnr_ldr']:.2f}" if m else "---")
        lines.append(f"{label} & " + " & ".join(cells) + " \\\\")
    lines += ["\\hline", "\\end{tabular}"]
    (args.output / "ablations.tex").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))

    # ---- Table 2.7: equivariance ablation -------------------------------
    lines = ["% Generated by scripts/figures/make_ablation_tables.py",
             "\\begin{tabular}{| l | c |}", "\\hline",
             "Equivariance & PSNR \\\\", "\\hline"]
    for label, rel in EQUIVARIANCE_ROWS:
        m = get(rel)
        lines.append(f"{label} & " +
                     (f"{m['psnr_ldr']:.2f}" if m else "---") + " \\\\")
    lines += ["\\hline", "\\end{tabular}"]
    (args.output / "equivariance.tex").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
